import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { css } from "../../styled-system/css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div
          className={css({
            display: "flex",
            height: "100vh",
          })}
        >
          <Sidebar />
          <main className={css({
            flex: 1,
            margin: "0.5rem 0.5rem 0.5rem 0",
            backgroundColor: "white",
            padding: '2.5rem',
            borderRadius: '1.25rem',
          })}>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
