import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { css } from "../../styled-system/css"

export const gilroyBold = localFont({
  src: '../fonts/Gilroy-Bold.ttf',
  display: 'swap',
  variable: '--font-gilroy-bold',
});

export const gilroyMedium = localFont({
  src: '../fonts/Gilroy-Medium.ttf',
  display: 'swap',
  variable: '--font-gilroy-medium',
});

export const gilroyRegular = localFont({
  src: '../fonts/Gilroy-Regular.ttf',
  display: 'swap',
  variable: '--font-gilroy-regular',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${gilroyBold.variable} ${gilroyMedium.variable} ${gilroyRegular.variable}`}
    >
      <body suppressHydrationWarning={true}>
        <div
          className={css({
            display: "flex",
            height: "100vh",
          })}
        >
          <Sidebar />
          <main className={css({
            flex: 1,
            margin: "0.5rem 0.5rem 0.5rem 0",
            backgroundColor: "white",
            padding: '2.5rem 2.5rem 0 2.5rem',
            borderRadius: '1.25rem',
          })}>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}